
name: Run Fan State Predictor

on:
  schedule:
    - cron: '*/10 * * * *'  # Every 10 minutes
  workflow_dispatch:        # Allow manual trigger

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas gspread oauth2client joblib influxdb-client scikit-learn shap

    - name: Run main.py
      env:
        GCP_CREDENTIALS_JSON: ${{ secrets.GCP_CREDENTIALS_JSON }}
        INFLUX_URL: ${{ secrets.INFLUX_URL }}
        INFLUX_TOKEN: ${{ secrets.INFLUX_TOKEN }}
        INFLUX_ORG: ${{ secrets.INFLUX_ORG }}
        INFLUX_BUCKET: ${{ secrets.INFLUX_BUCKET }}
      run: |
        python main.py
